import type { DocsPageContent } from "../types";

// Guides curated from docs/economy.html; the reference is generated from the bot's cogs (see docs/README.md).
export const economy: DocsPageContent = {
  slug: "economy",
  lead: "A full virtual economy — wallets, a bank, businesses, a stock market, a shop and casino-style games — plus a separate XP and leveling system with role rewards, and giveaways.",
  sections: [
    {
      id: "the-basics",
      title: "The basics",
      blocks: [
        {
          type: "commands",
          label: "Economy basics",
          commands: [
            { usage: "!balance [member]", description: "Check a wallet balance." },
            { usage: "!work", description: "Work a job to earn money (has a cooldown)." },
            { usage: "!daily", description: "Claim your daily reward." },
            { usage: "!deposit <amount>", description: "Move money between wallet and bank — banked money is safe from `!rob`." },
            { usage: "!pay <member> <amount>", description: "Send money to another member." },
            { usage: "!richest", description: "Server economy leaderboard." },
          ],
        },
      ],
      subsections: [
        {
          id: "games-and-risk",
          title: "Games & risk",
          blocks: [
            { type: "p", text: "Casino-style ways to grow (or lose) your balance: `!coinflip`, `!slots`, `!blackjack`, `!gamble`, `!risk`, and `!rob <member>` to try stealing from someone else's wallet (banked money is protected)." },
          ],
        },
        {
          id: "businesses-and-stocks",
          title: "Businesses & the stock market",
          blocks: [
            { type: "p", text: "Buy a business with `!buybusiness <business_type>`, then grow it with `!hire` and `!businessefficiency`, collect its income with `!collect` (or `!collectall` for every business you own), and optionally protect it with `!insurebusiness` — or sabotage a rival's with `!sabotage <target> <business_id>`." },
            { type: "p", text: "Separately, `!buyshares <symbol> <shares>` and `!sellshares` let you trade on the built-in stock market; check prices with `!stocks` and your holdings with `!portfolio`." },
          ],
        },
        {
          id: "poker",
          title: "Poker",
          blocks: [
            { type: "p", text: "A multiplayer Texas Hold'em table: `!pokercreate <buy_in> [max_players]` starts a table, others join in, and the host can end it early with `!pokercancel`." },
          ],
        },
      ],
    },
    {
      id: "leveling-and-xp",
      title: "Leveling & XP",
      blocks: [
        { type: "p", text: "A separate activity-based system: members earn XP for chatting and level up, with optional role rewards at chosen levels." },
        {
          type: "commands",
          label: "Leveling commands",
          commands: [
            { usage: "!rank [member]", description: "Check XP progress (`!leaderboard` shows the server ranking)." },
            { usage: "!levelreward <level> <role>", description: "Grant a role automatically at a given level (`!levelrewards` lists them all, `!levelrewardremove` removes one)." },
            { usage: "!levelchannels add/remove/list", description: "Restrict which channels actually grant XP." },
            { usage: "!setxpcooldown <seconds>", description: "How often a member can earn XP from talking (recommended 30–90s)." },
            { usage: "!leveltoggle", description: "Turn level-up announcements off entirely (`!xptoggle` does the same for XP gain)." },
          ],
        },
      ],
    },
    {
      id: "giveaways",
      title: "Giveaways",
      blocks: [
        { type: "p", text: "Run giveaways with role-based bonus entries and message-count requirements:" },
        { type: "code", title: "Start a giveaway", code: "!create <prize> <duration> <winners> [channel] [messages_required] [roles_bonus_entries]" },
        { type: "p", text: "Use `!reroll <message_id> <winners>` if a winner doesn't claim their prize, or `!end` / `!delete` to finish or cancel one early." },
      ],
    },
  ],
  reference: {
    groups: [
      {
        id: "wallet-games",
        title: "Wallet & games",
        commands: [
          { usage: "!addmoney <member> <amount>", description: "Add money to a user's wallet." },
          { usage: "!autobank <business_id>", description: "Toggle whether a business auto-banks collected income." },
          { usage: "!balance [member]", description: "View your balance or another user's balance.", aliases: ["bal", "money"] },
          { usage: "!bank [member]", description: "View your bank balance." },
          { usage: "!blackjack <amount>", description: "Play blackjack.", aliases: ["bj"] },
          { usage: "!business <business_id>", description: "View one business by ID." },
          { usage: "!businessefficiency <business_id> [amount]", description: "Upgrade business efficiency. Example: businessefficiency 4 3 / businessefficiency 4 max" },
          { usage: "!businesses", description: "View available businesses to buy." },
          { usage: "!businesslb", description: "Show the business leaderboard." },
          { usage: "!buy <item_id> [amount]", description: "Buy an item from the shop." },
          { usage: "!buybusiness <business_type>", description: "Buy a business." },
          { usage: "!buyshares <symbol> <shares>", description: "Buy shares from the stock market." },
          { usage: "!coinflip <choice> <amount>", description: "Flip a coin." },
          { usage: "!collect <business_id>", description: "Collect income from one business." },
          { usage: "!collectall", description: "Collect income from all your businesses." },
          { usage: "!daily", description: "Claim your daily reward." },
          { usage: "!deposit <amount>", description: "Deposit money into your bank.", aliases: ["dep"] },
          { usage: "!gamble <amount>", description: "Gamble your money." },
          { usage: "!hire <business_id> [amount]", description: "Hire workers for a business. Example: hire 4 3 / hire 4 max" },
          { usage: "!insurebusiness <business_id>", description: "Buy insurance for a business." },
          { usage: "!inventory [member]", description: "View your inventory." },
          { usage: "!item <item_id>", description: "View one item from the shop." },
          { usage: "!mybusinesses [member]", description: "List your businesses." },
          { usage: "!pay <member> <amount>", description: "Pay another user.", aliases: ["give"] },
          { usage: "!portfolio [member]", description: "View your stock portfolio." },
          { usage: "!removemoney <member> <amount>", description: "Remove money from a user's wallet." },
          { usage: "!resetmoney <member>", description: "Reset a user's wallet and bank." },
          { usage: "!richest", description: "Show the economy leaderboard.", aliases: ["ecolb", "moneylb"] },
          { usage: "!risk <amount>", description: "High risk, high reward." },
          { usage: "!rob <member>", description: "Attempt to rob another user." },
          { usage: "!sabotage <target> <business_id>", description: "Attempt to sabotage another user's business." },
          { usage: "!sellbusiness <business_id>", description: "Sell one of your businesses." },
          { usage: "!sellitem <item_id> [amount]", description: "Sell an item from your inventory." },
          { usage: "!sellshares <symbol> <shares>", description: "Sell shares from the stock market." },
          { usage: "!setmoney <member> <amount>", description: "Set a user's wallet balance." },
          { usage: "!shop", description: "View the item shop." },
          { usage: "!slots <amount>", description: "Play the slot machine." },
          { usage: "!stocks", description: "View the stock market." },
          { usage: "!switchbusiness <business_id> <business_type>", description: "Switch one business to another type." },
          { usage: "!upgradebusiness <business_id> [amount]", description: "Upgrade a business. Example: upgradebusiness 4 3 / upgradebusiness 4 max" },
          { usage: "!withdraw <amount>", description: "Withdraw money from your bank.", aliases: ["with"] },
          { usage: "!work", description: "Work to earn money." },
        ],
      },
      {
        id: "poker-commands",
        title: "Poker",
        commands: [
          { usage: "!pokercancel", description: "Cancel the current poker game (host only)." },
          { usage: "!pokercreate <buy_in> [max_players]", description: "Create a Texas Hold'em poker game for 2–4 players." },
        ],
      },
      {
        id: "leveling-xp",
        title: "Leveling & XP",
        commands: [
          { usage: "!addxp <member> <amount>", description: "Add XP to a user." },
          { usage: "!channel add <channel>" },
          { usage: "!channel remove <channel>" },
          { usage: "!leaderboard", description: "View the server leveling leaderboard.", aliases: ["lb"] },
          { usage: "!levelchannels", description: "Manage which channels give XP." },
          { usage: "!levelchannels add <channel>", description: "Allow a channel to give XP." },
          { usage: "!levelchannels list", description: "List all channels that can give XP." },
          { usage: "!levelchannels remove <channel>", description: "Remove a channel from XP-allowed channels." },
          { usage: "!levelchannels reset", description: "Reset XP channels so all channels can give XP again." },
          { usage: "!levelconfig", description: "View the server leveling configuration." },
          { usage: "!levelignore", description: "Manage leveling ignore lists." },
          { usage: "!levelignore channel" },
          { usage: "!levelignore list", description: "List ignored channels and roles for leveling." },
          { usage: "!levelignore role" },
          { usage: "!levelreward <level> <role>", description: "Set a role reward for a specific level." },
          { usage: "!levelrewardremove <level>", description: "Remove a level reward." },
          { usage: "!levelrewardreset", description: "Remove all level rewards." },
          { usage: "!levelrewards", description: "List all level reward roles." },
          { usage: "!leveltoggle <state>", description: "Enable or disable level-up messages." },
          { usage: "!rank [member]", description: "View your rank or another user's rank." },
          { usage: "!removexp <member> <amount>", description: "Remove XP from a user." },
          { usage: "!resetlevelchannel", description: "Reset the level-up channel back to the current channel." },
          { usage: "!resetxp <member>", description: "Reset a user's XP." },
          { usage: "!role add <role>" },
          { usage: "!role remove <role>" },
          { usage: "!setlevel <member> <level>", description: "Set a user's level directly." },
          { usage: "!setlevelchannel <channel>", description: "Set the channel where level-up messages are sent." },
          { usage: "!setxp <member> <amount>", description: "Set a user's XP directly." },
          { usage: "!setxpcooldown <seconds>", description: "Set the XP cooldown in seconds. Recommended: 30-90." },
          { usage: "!xpinfo <member>", description: "Show raw XP stats for a member." },
          { usage: "!xptoggle <state>", description: "Enable or disable XP gain completely." },
        ],
      },
      {
        id: "giveaways-commands",
        title: "Giveaways",
        commands: [
          { usage: "!create <prize> <duration> <winners> [channel] [messages_required] [roles_bonus_entries]", description: "Create a giveaway." },
          { usage: "!delete <message_id>", description: "Delete a giveaway." },
          { usage: "!end <message_id>", description: "End a giveaway." },
          { usage: "!giveaways", description: "List all ongoing giveaways." },
          { usage: "!host <role>", description: "Give perms to a role." },
          { usage: "!reroll <message_id> <winners>", description: "Reroll the winner(s) of a giveaway." },
        ],
      },
    ],
  },
};
