import type { DocsPageContent } from "../types";

// Guides curated from docs/fun.html; the reference is generated from the bot's cogs (see docs/README.md).
export const fun: DocsPageContent = {
  slug: "fun",
  lead: "Games, music playback, Spotify integration, server counters, webhook relays and bot appearance customization.",
  sections: [
    {
      id: "games",
      title: "Games (slash commands)",
      blocks: [
        { type: "p", text: "A full arcade of slash-command games, solo or with a friend: `/8ball`, `/coinflip`, `/slots`, `/blackjack` (with split & double down), `/higherlower`, `/hangman`, `/wordle`, `/trivia`, `/rps [member]`, `/tictactoe <member>`, `/connectfour <member>`, `/poker <member>` (multi-stage Texas Hold'em with community cards), `/uno` (multiplayer queue with House Rules) and `/pool` (open lobby for multiple players)." },
      ],
    },
    {
      id: "music",
      title: "Music",
      blocks: [
        { type: "p", text: "Standard voice-channel music playback: `!play <query>` to queue a track, `!skip`, `!pause`/`!resume`, `!stop`, `!queue [page]` (with `clear`, `move` and `remove` subcommands), `!volume <percentage>`, `!seek <position>`, `!repeat <mode>` and `!nowplaying`." },
        { type: "p", text: "Save your preferred setup with `!preset [name]`, and adjust server-wide playback rules (like DJ role or autoplay) under `!settings`." },
      ],
    },
    {
      id: "spotify",
      title: "Spotify",
      blocks: [
        { type: "p", text: "Deeper Spotify integration for members who link an account: `!spotify login` to connect, `!spotify play <query>` or `!spotify vc <query>` to play a track (or your current Spotify track) straight into voice chat, plus `now`/`nowplaying`, `like`/`unlike`, `queue`, `artists`/`tracks [timeframe]` for listening stats, and `!spotify code <code_or_url>` to render a scannable Spotify code." },
      ],
    },
    {
      id: "server-counters",
      title: "Server counters",
      blocks: [
        { type: "p", text: "Auto-updating voice or text channels that display a live stat (member count, boosts, etc.): `!counter add <option> [channel_type] [flags]` to create one, `!counter options` to see which stats are available, `!counter refresh` to force an update, and `!counter remove <channel>` to delete one." },
      ],
    },
    {
      id: "webhooks",
      title: "Webhooks",
      blocks: [
        { type: "p", text: "Send and manage messages through saved webhook identifiers instead of the raw webhook UI — handy for relaying content into a channel under a custom name and avatar: `!webhook create <channel> <name>`, `!webhook send <identifier> <payload>`, plus `edit`, `deletemsg`, `avatar`, `name`, `list` and `delete`." },
        { type: "p", text: "The slash version (`/send`) exposes the same thing as individual embed fields (title, description, color, footer, image, thumbnail) instead of one raw payload." },
      ],
    },
    {
      id: "bot-customization",
      title: "Bot customization",
      blocks: [
        { type: "p", text: "Give Pleed a server-specific identity: `!customize avatar [image_url]`, `!customize banner [image_url]` and `!customize bio <text>` change how the bot appears in your server specifically, without affecting other servers. Check current settings with `!customize view` and roll any of them back with `!customize reset <option>`." },
      ],
    },
  ],
  reference: {
    groups: [
      {
        id: "games-commands",
        title: "Games",
        commands: [
          { usage: "/8ball", description: "Ask the magic 8-ball any question via a form." },
          { usage: "/blackjack", description: "Play blackjack with split & double down." },
          { usage: "/coinflip", description: "Flip a coin for luck." },
          { usage: "/connectfour <member>", description: "Play Connect Four with a friend." },
          { usage: "/hangman", description: "Play a solo game of Hangman." },
          { usage: "/higherlower", description: "Guess if the next number will be higher or lower." },
          { usage: "/poker <member>", description: "Play a multi-stage Texas Hold'em poker match with community cards." },
          { usage: "/pool", description: "Host an open pool lobby for multiple players." },
          { usage: "/rps [member]", description: "Play Rock Paper Scissors solo or PvP." },
          { usage: "/slots", description: "Spin the casino slots." },
          { usage: "/tictactoe <member>", description: "Play a classic 2-player Tic-Tac-Toe match." },
          { usage: "/trivia", description: "Answer a trivia question." },
          { usage: "/uno", description: "Host a multiplayer UNO match queue with House Rules." },
          { usage: "/wordle", description: "Play Discord Wordle." },
        ],
      },
      {
        id: "music-commands",
        title: "Music",
        commands: [
          { usage: "!disconnect", aliases: ["dc", "leave"] },
          { usage: "!nowplaying", aliases: ["np", "current"] },
          { usage: "!pause" },
          { usage: "!play <query>", aliases: ["p"] },
          { usage: "!preset [name]" },
          { usage: "!preset active" },
          { usage: "!queue [page]", aliases: ["q"] },
          { usage: "!queue clear" },
          { usage: "!queue move <position> <new_position>", aliases: ["mv"] },
          { usage: "!queue remove <position>", aliases: ["delete", "rm"] },
          { usage: "!repeat <mode>", aliases: ["loop"] },
          { usage: "!resume", aliases: ["unpause"] },
          { usage: "!seek <position>" },
          { usage: "!settings" },
          { usage: "!settings autoplay <toggle>", aliases: ["auto"] },
          { usage: "!settings dj [role]" },
          { usage: "!skip", aliases: ["sk"] },
          { usage: "!stop" },
          { usage: "!volume <percentage>", aliases: ["vol"] },
        ],
      },
      {
        id: "spotify-commands",
        title: "Spotify",
        commands: [
          { usage: "!spotify [query]", description: "Main Spotify command. `!spotify <song name>` (or the `!spot` shortcut) plays a song in voice — add the artist to narrow it down.", aliases: ["spot"] },
          { usage: "!spotify artists [timeframe]", aliases: ["topartists"] },
          { usage: "!spotify clear" },
          { usage: "!spotify code <code_or_url>", aliases: ["submit"] },
          { usage: "!spotify device [device_query]", aliases: ["devices"] },
          { usage: "!spotify find <query>", aliases: ["searchsource"] },
          { usage: "!spotify join", description: "Joins your voice channel.", aliases: ["connectvc", "vconnect"] },
          { usage: "!spotify leave", aliases: ["disconnectvc", "vcleave", "vcdc"] },
          { usage: "!spotify like", aliases: ["save"] },
          { usage: "!spotify login", aliases: ["connect"] },
          { usage: "!spotify logout", aliases: ["disconnect"] },
          { usage: "!spotify next", aliases: ["skip"] },
          { usage: "!spotify now", aliases: ["musicnp", "vcnp"] },
          { usage: "!spotify nowplaying", aliases: ["np", "current"] },
          { usage: "!spotify pause" },
          { usage: "!spotify play <query>", description: "Plays a song in voice chat using Spotify metadata + yt-dlp audio source.", aliases: ["p"] },
          { usage: "!spotify previous", aliases: ["prev", "back"] },
          { usage: "!spotify queue [query]", aliases: ["add", "q"] },
          { usage: "!spotify remove <position>", aliases: ["rm"] },
          { usage: "!spotify repeat [mode]" },
          { usage: "!spotify resume", aliases: ["unpause"] },
          { usage: "!spotify seek <position>" },
          { usage: "!spotify shuffle [state]" },
          { usage: "!spotify tracks [timeframe]", aliases: ["toptracks"] },
          { usage: "!spotify unlike", aliases: ["unsave"] },
          { usage: "!spotify vc [query]", description: "Join your voice channel and play either: - your current Spotify track - a searched Spotify track if a query is provided", aliases: ["voice", "replicate", "sync"] },
          { usage: "!spotify vcstop", aliases: ["stopvc", "stop"] },
          { usage: "!spotify volume <percentage>", aliases: ["vol"] },
        ],
      },
      {
        id: "server-counters-commands",
        title: "Server counters",
        commands: [
          { usage: "!counter", aliases: ["counters"] },
          { usage: "!counter add <option> [channel_type] [flags]", description: "Add a counter, e.g. `!counter add members voice --name Members: {count}`." },
          { usage: "!counter options" },
          { usage: "!counter refresh", aliases: ["update"] },
          { usage: "!counter remove <channel>", aliases: ["delete", "del"] },
        ],
      },
      {
        id: "webhooks-commands",
        title: "Webhooks",
        commands: [
          { usage: "!webhook", aliases: ["webhooks", "wh"] },
          { usage: "!webhook avatar <identifier> [image_url]", description: "Change the avatar/image of a saved webhook.", aliases: ["image", "editavatar", "editimage"] },
          { usage: "!webhook create <channel> <name>", description: "Create a new webhook in the specified channel under a short identifier.", aliases: ["add", "new"] },
          { usage: "!webhook delete <identifier>", description: "Delete a saved webhook, after confirmation.", aliases: ["remove", "del"] },
          { usage: "!webhook deletemsg <message_link>", description: "Delete a message that was previously sent through this system.", aliases: ["delmsg"] },
          { usage: "!webhook edit <message_link> <new_message>", description: "Edit the embed content of a message previously sent through this system." },
          { usage: "!webhook list", description: "List every saved webhook in this server, paginated.", aliases: ["show", "all"] },
          { usage: "!webhook name <identifier> <new_name>", description: "Change the name of a saved webhook.", aliases: ["editname", "rename"] },
          { usage: "!webhook send <identifier> <payload>", description: "Send a message through a saved webhook." },
          { usage: "!webhook stats", description: "Developer-only: cross-guild webhook usage counts." },
          { usage: "!webhook variables", aliases: ["vars"] },
        ],
      },
      {
        id: "webhooks-slash",
        title: "Webhooks (slash)",
        commands: [
          { usage: "/avatar <identifier> [image_url]", description: "Change the avatar/image of a saved webhook" },
          { usage: "/create <channel> <name>", description: "Create a new relay webhook in a specified channel" },
          { usage: "/delete <identifier>", description: "Delete a saved webhook" },
          { usage: "/deletemsg <message_link>", description: "Delete a message previously sent through this system" },
          { usage: "/edit <message_link> <new_message>", description: "Edit the content inside a webhook message embed" },
          { usage: "/list", description: "List every saved webhook in this server" },
          { usage: "/name <identifier> <new_name>", description: "Change the name of a saved webhook" },
          { usage: "/send <identifier> [message] [embed_title] [embed_description] [embed_color] [embed_footer] [embed_image] [embed_thumbnail] [embed_json] [username] [avatar] [thread] [silent]", description: "Send a message through a saved webhook" },
          { usage: "/variables", description: "Show variables you can use in messages/embeds" },
        ],
      },
      {
        id: "bot-customization-commands",
        title: "Bot customization",
        commands: [
          { usage: "!customize", description: "Customize Pleed's server appearance.", aliases: ["customise", "customization"] },
          { usage: "!customize avatar [image_url]", description: "Set the server-custom bot avatar image.", aliases: ["pfp", "icon"] },
          { usage: "!customize banner [image_url]", description: "Set the server-custom bot banner image.", aliases: ["background"] },
          { usage: "!customize bio <text>", description: "Set the server-custom bot bio.", aliases: ["about", "description"] },
          { usage: "!customize help", description: "Show command usage." },
          { usage: "!customize reset <option>", description: "Reset avatar, banner, bio, or all.", aliases: ["clear", "remove"] },
          { usage: "!customize view", description: "View current customization settings.", aliases: ["show", "preview"] },
        ],
      },
    ],
  },
};
