import type { DocsPageContent } from "../types";

// Guides curated from docs/moderation.html; the reference is generated from the bot's cogs (see docs/README.md).
export const moderation: DocsPageContent = {
  slug: "moderation",
  lead: "Pleed's moderation suite covers the basics — kick, ban, timeout, warn — plus a full jail system, channel access control, command aliases, AutoMod, logging and role tools.",
  sections: [
    {
      id: "the-essentials",
      title: "The essentials",
      blocks: [
        { type: "p", text: "Standard actions work the way you'd expect from any moderation bot:" },
        {
          type: "commands",
          label: "Essential moderation commands",
          commands: [
            { usage: "!warn <member> [reason]", description: "Warn a member." },
            { usage: "!timeout <member> [duration] [reason]", description: "Timeout a member — durations like `10m`, `2h`, `3d`, `1w`." },
            { usage: "!kick <member> [reason]", description: "Kick a member from the server." },
            { usage: "!ban <member> [reason]", description: "Ban a member from the server." },
            { usage: "!softban <member> [reason]", description: "Ban, delete their last day of messages, then immediately unban." },
            { usage: "!hardban <user_id> [reason]", description: "Ban by ID and store the user in a persistent hardban registry (they stay banned even if unbanned manually)." },
            { usage: "!purge <amount>", description: "Bulk-delete messages in the current channel." },
          ],
        },
      ],
    },
    {
      id: "server-lockdown",
      title: "Server lockdown",
      blocks: [
        { type: "p", text: "For active raids, `!lockdown [reason]` locks every channel for @everyone in one shot, with an interactive Confirm/Cancel step on the slash version so you don't lock down by accident. `!unlockdown [reason]` reverses it. For a single channel, use `!lock [channel] [reason]` and `!unlock [channel] [reason]` instead." },
      ],
    },
    {
      id: "jail-system",
      title: "Jail system",
      blocks: [
        { type: "p", text: "Jailing is a softer alternative to banning: the member is stripped of their roles and given a restricted \"jailed\" role instead, so they stay in the server but can't interact until released." },
        {
          type: "commands",
          label: "Jail commands",
          commands: [
            { usage: "!jail <member> [duration] [reason]", description: "Jail a member, optionally for a set duration (e.g. `!jail @Bob 1h spamming`). Shows a Confirm/Cancel prompt by default." },
            { usage: "!sjail <member> [duration] [reason]", description: "Same as `!jail` but skips the confirmation step." },
            { usage: "!unjail <member> [reason]", description: "Release a member from jail immediately." },
            { usage: "!jailtime <member> <adjustment>", description: "Extend or shorten an active jail sentence." },
            { usage: "!jailpanel [member]", description: "Open an interactive management panel for jail actions." },
            { usage: "!jailconfirm on|off", description: "Toggle whether `!jail` requires the Confirm/Cancel step." },
            { usage: "!jailtemplate add <name> <duration> [reason]", description: "Save a reusable jail template (e.g. a \"spam\" template with a preset duration and reason) so repeat offenses are one command." },
          ],
        },
        { type: "callout", tone: "tip", text: "Need the jail role and channel first? `!setupjail` creates both — see [the setup center](/docs/server-setup#the-setup-center)." },
      ],
    },
  ],
  reference: {
    groups: [
      {
        id: "core-moderation",
        title: "Core moderation",
        commands: [
          { usage: "!ban <member> [reason]", description: "Ban a member from the server." },
          { usage: "!bind", description: "Bind moderation security settings." },
          { usage: "!bind staff [role]" },
          { usage: "!clearwarns <member>", description: "Clear all warnings for a member." },
          { usage: "!hardban <user_id> [reason]", description: "Hardban a user by ID and store them in the registry." },
          { usage: "!invoke", description: "Customize moderation invoke responses and DMs." },
          { usage: "!invoke ban <message_type> <message>" },
          { usage: "!invoke jail <message_type> <message>" },
          { usage: "!invoke kick <message_type> <message>" },
          { usage: "!kick <member> [reason]", description: "Kick a member from the server." },
          { usage: "!lock [channel] [reason]", description: "Lock a channel for @everyone." },
          { usage: "!lockdown [reason]", description: "Lock down the entire server immediately. Prefix version is not private." },
          { usage: "!mute <member> [duration_or_reason] [reason]" },
          { usage: "!purge <amount>", description: "Delete messages in the current channel." },
          { usage: "!removewarn <warn_id>", description: "Remove a specific warning by ID." },
          { usage: "!softban <member> [reason]", description: "Softban a member (ban, delete 1 day messages, then unban)." },
          { usage: "!staff list" },
          { usage: "!timeout <member> [duration] [reason]", description: "Timeout a member. Examples: 10m, 2h, 3d, 1w, or 60" },
          { usage: "!unban <user_id>", description: "Unban a user by ID." },
          { usage: "!unlock [channel] [reason]", description: "Unlock a channel for @everyone." },
          { usage: "!unlockdown [reason]", description: "Remove a server lockdown immediately. Prefix version is not private." },
          { usage: "!unmute <member> [reason]" },
          { usage: "!untimeout <member>", description: "Remove timeout from a member." },
          { usage: "!warn <member> [reason]", description: "Warn a member." },
          { usage: "!warnings <member>", description: "View a member's warnings." },
        ],
      },
      {
        id: "jail-system-commands",
        title: "Jail system",
        commands: [
          { usage: "!jail <member> [duration_or_reason] [reason]", description: "Jail a member, optionally for a set duration (e.g. `!jail @Bob 1h spamming`). Checks permissions and role hierarchy first. If jail confirmation is off for the server it jails immediately; if it's on, a qualified staff member has to press Confirm first.", aliases: ["prison"] },
          { usage: "!jailconfirm", description: "View or toggle whether `!jail` requires Confirm/Cancel buttons.", aliases: ["confirmjail"] },
          { usage: "!jailconfirm off", aliases: ["disable", "disabled", "false"] },
          { usage: "!jailconfirm on", aliases: ["enable", "enabled", "true"] },
          { usage: "!jailpanel [member]", description: "Open an interactive jail management panel: server-wide jail and mute counts and config, plus the member's status if given. Pick any member from the dropdown, browse the full jailed-members list, pull up a member's history, and jail or unjail them — all with buttons.", aliases: ["jinfo", "jailinfo"] },
          { usage: "!jailtemplate", description: "List saved quick-jail templates (or use `!jailtemplate add/remove`). Templates are duration + reason presets (e.g. \"spam\" → 1h, \"Spamming in channels\") that show up as one-click options in the `!jailpanel` \"Quick Jail\" dropdown, so common jail reasons don't need to be typed out every time.", aliases: ["jtemplate", "jailtemplates"] },
          { usage: "!jailtemplate add <name> <duration> [reason]", description: "Save a jail template — the duration accepts `1h`, `3d` and so on, or `perm` for none.", aliases: ["set"] },
          { usage: "!jailtemplate remove <name>", description: "Delete a saved jail template.", aliases: ["delete"] },
          { usage: "!jailtime <member> <adjustment>", description: "Change an active jail's expiry. The adjustment can be `+1h` / `-30m` (relative to the current expiry, or to now if the jail is permanent), `2h` / `3d` (reset to that duration from now), or `perm` / `permanent` / `none` (remove the expiry).", aliases: ["adjustjail"] },
          { usage: "!sjail <member> [duration_or_reason] [reason]", description: "Same as `!jail` but skips the confirm buttons and the \"you were jailed\" DM. Permission and hierarchy checks still apply.", aliases: ["silentjail"] },
          { usage: "!unjail <member> [reason]", description: "Release a member from jail immediately.", aliases: ["release"] },
        ],
      },
      {
        id: "automod",
        title: "AutoMod",
        commands: [
          { usage: "!automod", description: "Configure automod settings." },
          { usage: "!automod ignore" },
          { usage: "!automod logs <channel>", description: "Set automod log channel." },
          { usage: "!automod punishment <first> [second]", description: "Set the default punishment, or `automod punishment <category> <mode>` to override just one category (links, invites, spam, caps, mentions, repeats, badwords). Use `default` as the mode to clear a category override." },
          { usage: "!automod stats", description: "Show how often each automod category has triggered." },
          { usage: "!automod strikes [member]", description: "View a member's escalation strikes." },
          { usage: "!automod test <content>", description: "Check what a message would trigger without actually punishing anyone." },
          { usage: "!automod thresholds [setting] [value]", description: "View or set automod trigger thresholds." },
          { usage: "!automod toggle <feature> <state>", description: "Toggle an automod setting on or off." },
          { usage: "!automod words" },
          { usage: "!ignore channel <channel>", description: "Ignore a channel." },
          { usage: "!ignore role <role>", description: "Ignore a role." },
          { usage: "!ignore unchannel <channel>", description: "Stop ignoring a channel." },
          { usage: "!ignore unrole <role>", description: "Stop ignoring a role." },
          { usage: "!stats reset", description: "Clear recorded automod stats for this server." },
          { usage: "!strikes reset <member>", description: "Clear a member's strikes." },
          { usage: "!words add <word>", description: "Add a blocked word." },
          { usage: "!words remove <word>", description: "Remove a blocked word." },
        ],
      },
      {
        id: "channel-access-control",
        title: "Channel access control",
        commands: [
          { usage: "!access" },
          { usage: "!access clearlog" },
          { usage: "!access commandrules" },
          { usage: "!access panel" },
          { usage: "!access reset <channel>" },
          { usage: "!access rules [channel]" },
          { usage: "!access setlog <channel>" },
          { usage: "!access setup" },
          { usage: "!access sync [channel]" },
          { usage: "!accessclearlog", description: "Disable access logs." },
          { usage: "!accesspanel", description: "Open a private channel access manager panel." },
          { usage: "!accessreset <channel>", description: "Reset all saved access rules for a channel." },
          { usage: "!accessrules [channel]", description: "Show saved visibility rules for a channel." },
          { usage: "!accesssetlog <channel>", description: "Set the logs channel for access changes." },
          { usage: "!accesssetup", description: "Send the cleaner setup panel for access controls." },
          { usage: "!accesssync [channel]", description: "Re-apply all stored visibility rules." },
          { usage: "!commandrules", description: "Show bot command whitelist/blacklist channel rules." },
        ],
      },
      {
        id: "role-management",
        title: "Role management",
        commands: [
          { usage: "!color edit <args>", description: "Edit a role color. Use default, one hex, or two hex values separated by a comma.", aliases: ["set"] },
          { usage: "!dragrole <args>", description: "Create a role and place it directly below another role." },
          { usage: "!fetch", description: "Fetch things from the server." },
          { usage: "!fetch icon <role_query>", description: "Send a role's icon as a PNG file." },
          { usage: "!giverole <member> <role_query>", description: "Add a role to a member.", aliases: ["addrole"] },
          { usage: "!icon set [args]", description: "Set a role's icon from an attached image, replied image, or emoji.", aliases: ["update"] },
          { usage: "!newrole <name>", description: "Create a new role.", aliases: ["createrole"] },
          { usage: "!r [role_query]", description: "Open the premium roles panel, view role info, or toggle a role on a member.", aliases: ["role", "roles"] },
          { usage: "!r color [role_query]", description: "View or edit a role's color.", aliases: ["colour"] },
          { usage: "!r icon [role_query]", description: "View a role's icon, or use subcommands to manage it.", aliases: ["displayicon"] },
          { usage: "!r list", description: "Show every role in the server in a premium paged embed.", aliases: ["all", "directory"] },
          { usage: "!r members <role_query>", description: "View members in a role.", aliases: ["in", "memberlist"] },
          { usage: "!r perms <role_query>", description: "View a role's enabled permissions.", aliases: ["permissions"] },
          { usage: "!roledel <role_query>", description: "Delete a role.", aliases: ["deleterole"] },
          { usage: "!roleeditname <args>", description: "Rename a role.", aliases: ["renamerole"] },
          { usage: "!roleposition <args>", description: "Move a role to a specific position." },
          { usage: "!roleremove <member> <role_query>", description: "Remove a role from a member.", aliases: ["removerole", "takerole"] },
        ],
      },
      {
        id: "server-logging",
        title: "Server logging",
        commands: [
          { usage: "!channel add <channel>" },
          { usage: "!channel remove <channel>" },
          { usage: "!ignore channel" },
          { usage: "!ignore list", description: "List all ignored channels, roles, and users." },
          { usage: "!ignore role" },
          { usage: "!ignore user" },
          { usage: "!logs", description: "Manage advanced logging settings.", aliases: ["log"] },
          { usage: "!logs all <state>", description: "Turn every log type on or off." },
          { usage: "!logs ignore", description: "Manage logging ignores." },
          { usage: "!logs modules", description: "Show module states." },
          { usage: "!logs note [text]", description: "Set the textbox note shown on the control panel." },
          { usage: "!logs panel", description: "Open the interactive logging panel." },
          { usage: "!logs route <log_type> <channel>", description: "Route one log type to a different channel." },
          { usage: "!logs style <setting_name> <state>", description: "Toggle panel style options: compact_mode, include_thumbnails, show_footer" },
          { usage: "!logs test", description: "Send a test log embed." },
          { usage: "!logs toggle <log_type> <state>", description: "Toggle a specific log type." },
          { usage: "!logs unroute <log_type>", description: "Clear a custom route for one log type." },
          { usage: "!role add <role>" },
          { usage: "!role remove <role>" },
          { usage: "!setlogs <channel>", description: "Set the main logging channel.", aliases: ["setlog", "setlogchannel"] },
          { usage: "!user add <member>" },
          { usage: "!user remove <member>" },
        ],
      },
      {
        id: "command-aliases",
        title: "Command aliases",
        commands: [
          { usage: "!add <name> <command>", description: "Create a command alias." },
          { usage: "!adminonly <name> <enabled>", description: "Require Manage Server to use an alias." },
          { usage: "!alias" },
          { usage: "!alias add <name> <command>" },
          { usage: "!alias adminonly <name> <value>" },
          { usage: "!alias cooldown <name> <seconds>" },
          { usage: "!alias list" },
          { usage: "!alias remove <name>", aliases: ["delete"] },
          { usage: "!alias response <name> <response>" },
          { usage: "!alias view <name>" },
          { usage: "!cooldown <name> <seconds>", description: "Set a per-user cooldown on an alias." },
          { usage: "!list", description: "List all aliases." },
          { usage: "!remove <name>", description: "Remove an alias." },
          { usage: "!response <name> <response>", description: "Create a text or embed response alias." },
          { usage: "!view <name>", description: "View an alias." },
        ],
      },
      {
        id: "bump-reminders",
        title: "Bump reminders",
        commands: [
          { usage: "!bumpreminder", description: "View bump reminder help.", aliases: ["br"] },
          { usage: "!bumpreminder autoclean <state>" },
          { usage: "!bumpreminder autolock <state>" },
          { usage: "!bumpreminder channel <channel>" },
          { usage: "!bumpreminder config", aliases: ["settings"] },
          { usage: "!bumpreminder message <message>" },
          { usage: "!bumpreminder reset" },
          { usage: "!bumpreminder test" },
          { usage: "!bumpreminder thankyou <message>", aliases: ["thanks", "ty"] },
        ],
      },
    ],
  },
};
