import type { DocsPageContent } from "../types";

// Guides curated from docs/security.html; the reference is generated from the bot's cogs (see docs/README.md).
export const security: DocsPageContent = {
  slug: "security",
  lead: "Pleed's security layer watches for mass-destructive actions — mass bans, channel deletion, role deletion, webhook spam — and automatically punishes whoever triggers them. It also has a join gate for raid protection and rate limiting for command abuse.",
  sections: [
    {
      id: "setting-up-anti-nuke",
      title: "Setting up anti-nuke",
      blocks: [
        { type: "p", text: "Anti-nuke protects against compromised staff accounts or malicious bots by watching audit-log actions and punishing whoever crosses a threshold within a short window. Each module has its own independent threshold and punishment:" },
        {
          type: "table",
          label: "Anti-nuke modules",
          columns: ["Module", "Watches for"],
          rows: [
            ["`!antinuke ban`", "Bans"],
            ["`!antinuke kick`", "Kicks"],
            ["`!antinuke channel`", "Channel deletes"],
            ["`!antinuke role`", "Role deletes"],
            ["`!antinuke emoji`", "Emoji deletes"],
            ["`!antinuke webhook`", "Webhook creation"],
            ["`!antinuke botadd`", "Bot adds"],
            ["`!antinuke vanity`", "Vanity URL changes"],
          ],
        },
        {
          type: "steps",
          items: [
            "Run `!antinuke enable` to turn the system on for your server.",
            "Add trusted staff with `!antinuke admin @user` so they're exempt from punishment.",
            "Whitelist any bots or integrations that legitimately need to bulk-manage channels or roles with `!antinuke whitelist @user_or_role_or_id`.",
            "Tune individual modules — for example, `!antinuke ban on --threshold 3 --do ban` punishes an account that bans 3+ members quickly by banning them back.",
            "Review your setup any time with `!antinuke config` or `!antinuke list`.",
          ],
        },
        { type: "code", title: "Example — ban anyone who bans 3+ members quickly", code: "!antinuke ban on --threshold 3 --do ban" },
        { type: "callout", tone: "warning", title: "Bot permissions", text: "Anti-nuke needs **View Audit Log**, and Pleed's role must sit above the accounts it may need to punish, or it won't be able to act in time." },
      ],
    },
    {
      id: "join-gate",
      title: "Join gate / anti-alt",
      blocks: [
        { type: "p", text: "Screens new joins for very new or suspicious accounts (common in raid bot waves) and can hold them back from full access until they pass your checks. The commands live under [Join gate / anti-alt](#join-gate-commands) in the reference below." },
      ],
    },
    {
      id: "rate-limiting",
      title: "Rate limiting",
      blocks: [
        { type: "p", text: "Throttles command spam so a single user (or a compromised account) can't hammer moderation or economy commands to cause disruption." },
      ],
    },
  ],
  reference: {
    groups: [
      {
        id: "antinuke-protection",
        title: "Anti-nuke protection",
        commands: [
          { usage: "!admin remove <user>", aliases: ["delete", "del"] },
          { usage: "!antinuke", description: "Configure antinuke protection.", aliases: ["an"] },
          { usage: "!antinuke admin [user]" },
          { usage: "!antinuke admins" },
          { usage: "!antinuke ban [status] <args>" },
          { usage: "!antinuke botadd [status] <args>" },
          { usage: "!antinuke channel [status] <args>" },
          { usage: "!antinuke config", aliases: ["settings"] },
          { usage: "!antinuke disable" },
          { usage: "!antinuke emoji [status] <args>" },
          { usage: "!antinuke enable" },
          { usage: "!antinuke kick [status] <args>" },
          { usage: "!antinuke list", aliases: ["modules"] },
          { usage: "!antinuke role [status] <args>" },
          { usage: "!antinuke vanity [status] <args>" },
          { usage: "!antinuke webhook [status] <args>" },
          { usage: "!antinuke whitelist [target]", aliases: ["wl"] },
          { usage: "!whitelist remove <target>", aliases: ["delete", "del"] },
        ],
      },
      {
        id: "join-gate-commands",
        title: "Join gate / anti-alt",
        commands: [
          { usage: "!blacklist add <member>", description: "Add a user to the Join Gate blacklist." },
          { usage: "!blacklist remove <member>", description: "Remove a user from the Join Gate blacklist.", aliases: ["delete"] },
          { usage: "!joingate", description: "Configure Join Gate verification.", aliases: ["jg"] },
          { usage: "!joingate accountage <days>", description: "Set the minimum account age in days required to verify.", aliases: ["minage"] },
          { usage: "!joingate autokick <minutes>", description: "Set auto-kick time in minutes for unverified members. Use 0 to disable." },
          { usage: "!joingate blacklist", description: "Manage Join Gate blacklist users." },
          { usage: "!joingate bypassrole <role>", description: "Set the bypass role that skips Join Gate.", aliases: ["bypass"] },
          { usage: "!joingate channel <channel>", description: "Set the verification channel.", aliases: ["verifychannel"] },
          { usage: "!joingate clearbypassrole", description: "Clear the Join Gate bypass role." },
          { usage: "!joingate clearlogchannel", description: "Clear the Join Gate-specific log channel." },
          { usage: "!joingate disable", description: "Disable Join Gate." },
          { usage: "!joingate dmonjoin <state>", description: "Enable or disable Join Gate DMs on member join.", aliases: ["dm"] },
          { usage: "!joingate enable", description: "Enable Join Gate." },
          { usage: "!joingate lockverify", description: "Lock down the verify channel for Join Gate." },
          { usage: "!joingate logchannel <channel>", description: "Set a Join Gate-specific log channel.", aliases: ["logs"] },
          { usage: "!joingate panel", description: "Send, detect, or refresh the Join Gate verification panel.", aliases: ["refreshpanel"] },
          { usage: "!joingate permissions", description: "Check verify channel permissions for Join Gate.", aliases: ["perms"] },
          { usage: "!joingate reset", description: "Reset all Join Gate settings." },
          { usage: "!joingate resetpanel", description: "Forget the stored panel message ID. This does not delete the panel." },
          { usage: "!joingate reverify <member>", description: "Force a member to go through Join Gate again." },
          { usage: "!joingate scanpanel", description: "Scan the verification channel and remember the existing panel.", aliases: ["detectpanel"] },
          { usage: "!joingate status", description: "Show Join Gate status." },
          { usage: "!joingate unlockverify", description: "Remove the forced verified-role hide from the verify channel." },
          { usage: "!joingate unverifiedrole <role>", description: "Set the unverified role.", aliases: ["unverified"] },
          { usage: "!joingate verifiedrole <role>", description: "Set the verified role.", aliases: ["verified"] },
          { usage: "!joingate whitelist", description: "Manage Join Gate whitelist users." },
          { usage: "!verify", description: "Verify yourself through Join Gate." },
          { usage: "!whitelist add <member>", description: "Add a user to the Join Gate whitelist." },
          { usage: "!whitelist remove <member>", description: "Remove a user from the Join Gate whitelist.", aliases: ["delete"] },
        ],
      },
      {
        id: "kick-trap",
        title: "Kick trap",
        commands: [
          { usage: "!image add", description: "Add an attached image or replied-to message image to the recurring scam database." },
          { usage: "!image clear", description: "Clear all scam image hashes for this server." },
          { usage: "!image list", description: "List all registered scam image hashes." },
          { usage: "!intel add <domain>" },
          { usage: "!intel remove <domain>" },
          { usage: "!kicktrap", aliases: ["ktrap"] },
          { usage: "!kicktrap autokick <toggle>" },
          { usage: "!kicktrap boostertimeout [minutes]", aliases: ["booster", "boosters", "timeoutboosters"] },
          { usage: "!kicktrap clearroles <user_id>", description: "Manually purge saved roles for a user so they join fresh.", aliases: ["clearrole"] },
          { usage: "!kicktrap flags [member]" },
          { usage: "!kicktrap image", description: "Manage visual scam image hashes." },
          { usage: "!kicktrap intel" },
          { usage: "!kicktrap list" },
          { usage: "!kicktrap logs [channel]", aliases: ["log"] },
          { usage: "!kicktrap quarantine", description: "Opens an interactive setup panel to configure quarantine settings." },
          { usage: "!kicktrap recover <member>", description: "Manually un-quarantines/recovers a member, removes restrictions, and restores their saved roles.", aliases: ["verify", "unlock", "untimeout"] },
          { usage: "!kicktrap remove [channel]", aliases: ["delete", "off"] },
          { usage: "!kicktrap resend [channel]" },
          { usage: "!kicktrap scam <toggle>" },
          { usage: "!kicktrap set [channel]", aliases: ["add", "channel"] },
          { usage: "!kicktrapresend", description: "Resend the warning embed in the current trap channel." },
          { usage: "!listkicktraps", description: "List all kick trap channels in this server.", aliases: ["kicktraps"] },
          { usage: "!removekick", description: "Remove the kick trap from the current channel." },
          { usage: "!setupkick", description: "Turn the current channel into a kick trap." },
          { usage: "!synctraps", description: "Scans all registered KickTrap channels, finds existing embed message IDs, and registers them in the database for updates." },
        ],
      },
      {
        id: "fake-permissions",
        title: "Fake permissions",
        commands: [
          { usage: "!fakepermissions", description: "Manage role fake permissions.", aliases: ["fakeperms", "fp"] },
          { usage: "!fakepermissions add <role> <permissions>", description: "Grant fake permissions to a role.", aliases: ["grant"] },
          { usage: "!fakepermissions check [member]", description: "Check fake permissions for a member.", aliases: ["inspect"] },
          { usage: "!fakepermissions list [role]", description: "View fake permissions.", aliases: ["view", "show"] },
          { usage: "!fakepermissions permissions", description: "List valid fake permission names.", aliases: ["valid"] },
          { usage: "!fakepermissions preset <role> <preset>", description: "Apply a recommended fake permission preset.", aliases: ["recommended"] },
          { usage: "!fakepermissions remove <role> <permissions>", description: "Revoke fake permissions from a role.", aliases: ["revoke"] },
          { usage: "!fakepermissions reset [role]", description: "Reset all fake permissions, or only one role.", aliases: ["clear"] },
        ],
      },
      {
        id: "rate-limiting-commands",
        title: "Rate limiting",
        commands: [
          { usage: "!rlpanel", description: "Open an interactive control panel to fine-tune rate limiting." },
        ],
      },
    ],
  },
};
