import type { DocsPageContent } from "../types";

// Guides curated from docs/utility.html; the reference is generated from the bot's cogs (see docs/README.md).
export const utility: DocsPageContent = {
  slug: "utility",
  lead: "Lookups, profile tools, snipe (recover deleted and edited messages), highlights, image utilities, and general server and member info for everyday use.",
  sections: [
    {
      id: "everyday-info",
      title: "Everyday info commands",
      blocks: [
        {
          type: "commands",
          label: "Everyday info commands",
          commands: [
            { usage: "!userinfo [member]", description: "Full info about a member." },
            { usage: "!serverinfo [guild_id]", description: "Full info about a server." },
            { usage: "!avatar [user]", description: "Grab a member's avatar or profile banner." },
            { usage: "!afk [reason]", description: "Set an AFK status shown when you're mentioned." },
            { usage: "!ping", description: "Check bot latency." },
          ],
        },
      ],
    },
    {
      id: "snipe",
      title: "Snipe (recover deleted content)",
      blocks: [
        { type: "p", text: "Snipe lets you look back at deleted messages, edits and ghost pings in a channel:" },
        {
          type: "commands",
          label: "Snipe commands",
          commands: [
            { usage: "!snipe [index]", description: "The last deleted message in this channel (or the Nth back)." },
            { usage: "!editsnipe [index]", description: "The last edited message." },
            { usage: "!ghostsnipe [index]", description: "Pings that were deleted quickly (\"ghost pings\")." },
            { usage: "!guildsnipe [index]", description: "Deleted messages anywhere in the server, not just the current channel." },
            { usage: "!usersnipe <member> [index]", description: "Filter sniped messages down to one member." },
            { usage: "!bulksnipe [index]", description: "Recover a bulk-delete event." },
            { usage: "!snipesearch <query>", description: "Search sniped content by keyword." },
          ],
        },
        {
          type: "list",
          items: [
            "Paginated browsing panels: `!snipepanel`, `!editsnipepanel`, `!ghostpanel`, `!reactionhistorypanel`.",
            "Cleanup: `!clearsnipe`, `!cleardeletedsnipes`, `!cleareditsnipes`, `!clearghostsnipes`.",
          ],
        },
      ],
    },
    {
      id: "highlights",
      title: "Highlights",
      blocks: [
        { type: "p", text: "Get notified (via DM) when a keyword you care about is mentioned, even if you weren't tagged: `!highlight add <keyword>`, view them with `!highlight list`, and use `!highlight ignore [target]` to mute notifications from a specific member, channel or role." },
      ],
    },
    {
      id: "social-and-game-lookups",
      title: "Social & game lookups",
      blocks: [
        { type: "p", text: "Pull public profile info from other platforms without leaving Discord: `!roblox <username>` (plus `fromdiscord`/`todiscord` account linking and `outfits`), `!minecraft <username>`, `!steam <steam_id>`, `!github <username>`, `!osu <username> [game]`, `!valorant <user>`, `!xbox <gamertag>`, `!snapchat <username>`, `!telegram <username>` and `!cashapp <username>`." },
      ],
    },
    {
      id: "image-tools",
      title: "Image tools",
      blocks: [
        { type: "p", text: "Quick image manipulation straight in chat: `!invert [url]`, `!rotate <degree> [url]`, `!compress <ratio> [url]`, `!hex [target]` (grab a dominant color), and `!screenshot <url>` to capture a website." },
      ],
    },
    {
      id: "emoji-and-stickers",
      title: "Emoji & stickers",
      blocks: [
        { type: "p", text: "Server emote and sticker management: `!emoji add <emoji> [name]`, `!emoji addmany <emotes>`, `!emoji rename`, `!emoji removeduplicates`, and the equivalent `!sticker add/remove/rename/cleanup` set for stickers." },
      ],
    },
  ],
  reference: {
    groups: [
      {
        id: "general-info",
        title: "General info",
        commands: [
          { usage: "!afk [reason]", description: "Set your AFK status." },
          { usage: "!avatar [user]", description: "Get avatar of a member or yourself.", aliases: ["av"] },
          { usage: "!banner [user]", description: "Get the banner of a member or yourself." },
          { usage: "!boosters", description: "View all recent server boosters." },
          { usage: "!boosters lost", description: "View list of most recent lost boosters." },
          { usage: "!bots", description: "View all bots in the server." },
          { usage: "!channelinfo [channel]", description: "View information about a channel." },
          { usage: "!donate", description: "Donate to the bot's hosting expenses." },
          { usage: "!emotes", description: "View all emotes in the server." },
          { usage: "!firstmessage", description: "Jump to the first message in the current channel." },
          { usage: "!guildbanner <guild_id>", description: "Returns banner icon." },
          { usage: "!guildicon <guild_id>", description: "Returns guild icon." },
          { usage: "!hide [channel]", description: "Hide a channel from @everyone." },
          { usage: "!inviteinfo <code>", description: "View basic invite code information." },
          { usage: "!membercount", description: "View server member count." },
          { usage: "!ping", description: "Check the bot latency." },
          { usage: "!seen <member>", description: "Seen when a member was last seen in the server." },
          { usage: "!serveravatar [user]", description: "Get the server avatar of a member or yourself." },
          { usage: "!serverbanner [user]", description: "Get the server banner of a member or yourself." },
          { usage: "!servericon", description: "Show the server icon." },
          { usage: "!serverinfo [guild_id]", description: "View information about a server." },
          { usage: "!splash <guild_id>", description: "Returns splash background." },
          { usage: "!status", description: "Get a link to the status page." },
          { usage: "!timezone [member]", description: "View your current time or somebody elses." },
          { usage: "!timezone list", description: "View a list of every member's timezone." },
          { usage: "!timezone set <location>", description: "Set your timezone." },
          { usage: "!unhide [channel]", description: "Unhide a channel for @everyone." },
          { usage: "!userinfo [member]", description: "View information about a member or yourself.", aliases: ["ui"] },
          { usage: "!weather <city>", description: "Gets simple weather from OpenWeatherMap." },
        ],
      },
      {
        id: "snipe-commands",
        title: "Snipe",
        commands: [
          { usage: "!bulksnipe [index]", description: "Snipe a bulk delete event in this channel.", aliases: ["bs"] },
          { usage: "!cleardeletedsnipes", description: "Clear only deleted-message snipes in this channel." },
          { usage: "!cleareditsnipes", description: "Clear only edit snipes in this channel." },
          { usage: "!clearghostsnipes", description: "Clear only ghost ping snipes in this channel." },
          { usage: "!clearsnipe", description: "Clear all snipes in this channel.", aliases: ["cs"] },
          { usage: "!editsnipe [index]", description: "Snipe an edited message.", aliases: ["es"] },
          { usage: "!editsnipepanel", description: "Open a paginated edit-snipe panel.", aliases: ["esp"] },
          { usage: "!ghostpanel", description: "Open a paginated ghost ping panel.", aliases: ["gsp"] },
          { usage: "!ghostsnipe [index]", description: "Snipe ghost pings in this channel.", aliases: ["gs"] },
          { usage: "!guildsnipe [index]", description: "Snipe deleted messages anywhere in the server.", aliases: ["gsn"] },
          { usage: "!reactionhistory [index]", description: "View reaction history in this channel.", aliases: ["rh"] },
          { usage: "!reactionhistorypanel", description: "Open a paginated reaction history panel.", aliases: ["rhp"] },
          { usage: "!reactionsnipe [index]", description: "Snipe a removed reaction.", aliases: ["rs"] },
          { usage: "!snipe [index]", description: "Snipe deleted messages in the current channel.", aliases: ["s"] },
          { usage: "!snipelist", description: "List recent deleted messages in this channel.", aliases: ["sl"] },
          { usage: "!snipepanel", description: "Open a paginated deleted-message snipe panel.", aliases: ["sp"] },
          { usage: "!snipesearch <query>", description: "Search deleted messages in this channel.", aliases: ["ss"] },
          { usage: "!snipestats", description: "Show snipe stats for this channel.", aliases: ["sstats"] },
          { usage: "!usersnipe <member> [index]", description: "Snipe deleted messages from a specific member in this channel.", aliases: ["us"] },
        ],
      },
      {
        id: "highlights-commands",
        title: "Highlights",
        commands: [
          { usage: "!highlight", description: "Set notifications for when a keyword is said." },
          { usage: "!highlight add <keyword>", description: "Add a highlighted keyword." },
          { usage: "!highlight ignore [target]", description: "Ignore notifications from members or a channel or a role." },
          { usage: "!highlight list", description: "List all keywords set in a server." },
          { usage: "!highlight remove <keyword>", description: "Remove a highlighted keyword." },
          { usage: "!highlight reset", description: "Reset your highlighted keywords in the current server." },
          { usage: "!ignore list", description: "List all ignored members, channel & roles." },
        ],
      },
      {
        id: "profiles-lookups",
        title: "Profiles & lookups",
        commands: [
          { usage: "!cashapp <username>", description: "Retrieve simple CashApp profile information." },
          { usage: "!define <word>", description: "Get definition of a word." },
          { usage: "!github <username>", description: "Gets profile information on the given Github user." },
          { usage: "!minecraft <username>", description: "Gets minecraft profile information." },
          { usage: "!osu <username> [game]", description: "Retrieve simple OSU! profile information." },
          { usage: "!roblox <username>", description: "Gets profile information on the given Roblox user." },
          { usage: "!roblox fromdiscord <user_id>", description: "Get Roblox account from Discord account." },
          { usage: "!roblox outfits <username>", description: "View all outfits for a user." },
          { usage: "!roblox template <asset_id>", description: "Download asset for an item." },
          { usage: "!roblox todiscord <username>", description: "Get Discord account from Roblox account." },
          { usage: "!snapchat <username>", description: "Get bitmoji and QR scan code for user." },
          { usage: "!snapchatstory <username>", description: "Gets all current stories for the given Snapchat user." },
          { usage: "!steam <steam_id>", description: "Get information about a steam profile." },
          { usage: "!telegram <username>", description: "Gets profile information on the given Telegram user or group." },
          { usage: "!urbandictionary <word>", description: "Gets the definition of a word/slang from Urban Dictionary." },
          { usage: "!valorant <user>", description: "Get valorant player information." },
          { usage: "!xbox <gamertag>", description: "Gets profile information on the given Xbox gamertag." },
        ],
      },
      {
        id: "image-tools-commands",
        title: "Image tools",
        commands: [
          { usage: "!compress <ratio> [url]", description: "Compress image to lower quality." },
          { usage: "!hex [target]", description: "Grab the most dominant color from an image." },
          { usage: "!invert [url]", description: "Invert an image's colors." },
          { usage: "!rotate <degree> [url]", description: "Rotate an image by a provided degree." },
          { usage: "!screenshot <url>", description: "Get an image of a website." },
        ],
      },
      {
        id: "emoji-stickers",
        title: "Emoji & stickers",
        commands: [
          { usage: "!emoji [emoji]", description: "Returns a large emoji or server emote" },
          { usage: "!emoji add <emoji> [characters]", description: "Downloads emote and adds to server" },
          { usage: "!emoji addmany <emotes>", description: "Bulk add emotes to the current server" },
          { usage: "!emoji information <message_link>", description: "View the most recent emote used" },
          { usage: "!emoji remove <emoji>", description: "Removes emote from server" },
          { usage: "!emoji removeduplicates", description: "Remove duplicates of emotes" },
          { usage: "!emoji removemany <emotes>", description: "Bulk remove emotes from the current server" },
          { usage: "!emoji rename <emoji> <new_name>", description: "Renames emote to the new name provided" },
          { usage: "!emoji stats", description: "Show top ten most used emotes" },
          { usage: "!sticker", description: "Modfy or add stickers to your server!" },
          { usage: "!sticker add <url> <name>", description: "Downloads sticker and adds to server" },
          { usage: "!sticker cleanup", description: "Cleans server sticker names" },
          { usage: "!sticker remove <name>", description: "Removes sticker from server" },
          { usage: "!sticker rename <new_name>", description: "Rename the attached sticker to given new name" },
          { usage: "!sticker tag", description: "Add server vanity to stickers" },
        ],
      },
      {
        id: "birthdays",
        title: "Birthdays",
        commands: [
          { usage: "!birthday [member]", description: "View your birthday or somebody elses." },
          { usage: "!birthday celebrate <role>", description: "Limit birthday celebration to members in certain roles." },
          { usage: "!birthday channel [channel]", description: "Set the birthday channel." },
          { usage: "!birthday config", description: "Set the birthday role." },
          { usage: "!birthday list", description: "View a list of every member's birthday." },
          { usage: "!birthday lock", description: "Lock the birthday system." },
          { usage: "!birthday role <role>", description: "Set the birthday role." },
          { usage: "!birthday set <date>", description: "Set your birthday." },
          { usage: "!birthday unlock", description: "Unlock the birthday system." },
          { usage: "!celebrate list", description: "List celebrated roles." },
        ],
      },
    ],
  },
};
